# Generated by Django 3.2.18 on 2023-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='financial_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('open_price', models.CharField(max_length=30)),
                ('close_price', models.CharField(max_length=30)),
                ('volume', models.CharField(max_length=30)),
            ],
        ),
    ]
